version: '3.8'

services:
  assessment_service:
    image: mrksdh/assessment
    ports:
      - "8080:8080"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - assessment_service
